CREATE TABLE MEMBERS(
	id VARCHAR(20) PRIMARY KEY,
	name VARCHAR(10) NOT NULL UNIQUE,
	passwd VARCHAR(30) NOT NULL,
	email VARCHAR(30)
);

CREATE TABLE Recommend(
	number INT(10) PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	script VARCHAR(300) NOT NULL
);

CREATE TABLE Question(
	number INT(10) PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	script VARCHAR(300) NOT NULL
);